#!/bin/bash
################################################################################
# 
# Copyright (c) 2019 NUAA AeroLab
# 
# @author   Jiang Yang (pokerpoke@qq.com)
# @date     2018-08
# @brief    
# @version  0.0.1
# 
# Last Modified:  2019-05-21
# Modified By:    Jiang Yang (pokerpoke@qq.com)
# 
################################################################################
set -e
set -x

# get scripts directory
CMAKE_SOURCE_DIR=$(dirname $(readlink -f $0))
# update cmake source path
CMAKE_SOURCE_DIR=$(pwd)
cd ${CMAKE_SOURCE_DIR}

if [ ! -d ./build ] 
then
   mkdir build 
fi

XXX=`ls src/ | grep  -E "^$1\." | awk -F '.cc' '{print $1}'`

cd build && cmake ..  && make $XXX -j8 && cd src 

./$XXX

set +x